name: Search and Notify
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5-17 * * 1-5'  # working hours

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry==1.8.2
        poetry install

    - name: Crawl courses
      run: poetry run scrapy crawl drs

    - name: Notify
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: poetry run python bot.py

    - name: Update courses CSV
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: '*.csv'
        commit_message: Update courses CSV once again
