name: Search and Notify
on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry==1.8.2
        poetry install

    - name: Crawl courses
      run: scrapy crawl drs

    - name: Notify
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python bot.py

    - name: Update courses CSV
      run: |
        git config --global user.name "DRS GitHub"
        git config --global user.email "DRSGitHub@users.noreply.github.com"
        git commit -a -m "Update courses CSV once again"
        git push origin main
